// Generated by https://quicktype.io

export interface LocationResponse {
  name: string;
  local_names: LocalNames;
  lat: number;
  lon: number;
  country: string;
}

export interface LocalNames {
  lt: string;
  no: string;
  fa: string;
  et: string;
  fi: string;
  hu: string;
  zh: string;
  la: string;
  ar: string;
  ru: string;
  mk: string;
  sv: string;
}

export interface LocationCoordinates {
  lat: number;
  lon: number;
}
